/*
 * Fava - OpenApi Gateway - DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopinto

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
)

// Linger please
var (
	_ _context.Context
)

type RecordsApi interface {

	/*
	 * DnsApiRecordsDelete Deletes records which match the specified criterias
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiDnsApiRecordsDeleteRequest
	 */
	DnsApiRecordsDelete(ctx _context.Context) ApiDnsApiRecordsDeleteRequest

	/*
	 * DnsApiRecordsDeleteExecute executes the request
	 */
	DnsApiRecordsDeleteExecute(r ApiDnsApiRecordsDeleteRequest) (*_nethttp.Response, GenericOpenAPIError)

	/*
	 * DnsApiRecordsGet Retrieves the DNS zone's resource records
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiDnsApiRecordsGetRequest
	 */
	DnsApiRecordsGet(ctx _context.Context) ApiDnsApiRecordsGetRequest

	/*
	 * DnsApiRecordsGetExecute executes the request
	 * @return []Record
	 */
	DnsApiRecordsGetExecute(r ApiDnsApiRecordsGetRequest) ([]Record, *_nethttp.Response, GenericOpenAPIError)

	/*
	 * DnsApiRecordsPost Creates a new DNS resource record
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiDnsApiRecordsPostRequest
	 */
	DnsApiRecordsPost(ctx _context.Context) ApiDnsApiRecordsPostRequest

	/*
	 * DnsApiRecordsPostExecute executes the request
	 * @return Record
	 */
	DnsApiRecordsPostExecute(r ApiDnsApiRecordsPostRequest) (Record, *_nethttp.Response, GenericOpenAPIError)
}

// RecordsApiService RecordsApi service
type RecordsApiService service

type ApiDnsApiRecordsDeleteRequest struct {
	ctx         _context.Context
	ApiService  RecordsApi
	zone        *string
	recordType  *RecordType
	name        *string
	xApiOptions *string
}

func (r ApiDnsApiRecordsDeleteRequest) Zone(zone string) ApiDnsApiRecordsDeleteRequest {
	r.zone = &zone
	return r
}
func (r ApiDnsApiRecordsDeleteRequest) RecordType(recordType RecordType) ApiDnsApiRecordsDeleteRequest {
	r.recordType = &recordType
	return r
}
func (r ApiDnsApiRecordsDeleteRequest) Name(name string) ApiDnsApiRecordsDeleteRequest {
	r.name = &name
	return r
}
func (r ApiDnsApiRecordsDeleteRequest) XApiOptions(xApiOptions string) ApiDnsApiRecordsDeleteRequest {
	r.xApiOptions = &xApiOptions
	return r
}

func (r ApiDnsApiRecordsDeleteRequest) Execute() (*_nethttp.Response, GenericOpenAPIError) {
	return r.ApiService.DnsApiRecordsDeleteExecute(r)
}

/*
 * DnsApiRecordsDelete Deletes records which match the specified criterias
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiDnsApiRecordsDeleteRequest
 */
func (a *RecordsApiService) DnsApiRecordsDelete(ctx _context.Context) ApiDnsApiRecordsDeleteRequest {
	return ApiDnsApiRecordsDeleteRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 */
func (a *RecordsApiService) DnsApiRecordsDeleteExecute(r ApiDnsApiRecordsDeleteRequest) (*_nethttp.Response, GenericOpenAPIError) {
	var (
		localVarHTTPMethod   = _nethttp.MethodDelete
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		executionError       GenericOpenAPIError
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RecordsApiService.DnsApiRecordsDelete")
	if err != nil {
		executionError.error = err.Error()
		return nil, executionError
	}

	localVarPath := localBasePath + "/dns/api/Records"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.zone == nil {
		executionError.error = "zone is required and must be specified"
		return nil, executionError
	}
	if r.recordType == nil {
		executionError.error = "recordType is required and must be specified"
		return nil, executionError
	}
	if r.name == nil {
		executionError.error = "name is required and must be specified"
		return nil, executionError
	}
	if r.xApiOptions == nil {
		executionError.error = "xApiOptions is required and must be specified"
		return nil, executionError
	}

	localVarQueryParams.Add("Zone", parameterToString(*r.zone, ""))
	localVarQueryParams.Add("RecordType", parameterToString(*r.recordType, ""))
	localVarQueryParams.Add("Name", parameterToString(*r.name, ""))
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["x-api-options"] = parameterToString(*r.xApiOptions, "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		executionError.error = err.Error()
		return nil, executionError
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		executionError.error = err.Error()
		return localVarHTTPResponse, executionError
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		executionError.error = err.Error()
		return localVarHTTPResponse, executionError
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, executionError
}

type ApiDnsApiRecordsGetRequest struct {
	ctx         _context.Context
	ApiService  RecordsApi
	zone        *string
	xApiOptions *string
	recordType  *RecordType
	name        *string
}

func (r ApiDnsApiRecordsGetRequest) Zone(zone string) ApiDnsApiRecordsGetRequest {
	r.zone = &zone
	return r
}
func (r ApiDnsApiRecordsGetRequest) XApiOptions(xApiOptions string) ApiDnsApiRecordsGetRequest {
	r.xApiOptions = &xApiOptions
	return r
}
func (r ApiDnsApiRecordsGetRequest) RecordType(recordType RecordType) ApiDnsApiRecordsGetRequest {
	r.recordType = &recordType
	return r
}
func (r ApiDnsApiRecordsGetRequest) Name(name string) ApiDnsApiRecordsGetRequest {
	r.name = &name
	return r
}

func (r ApiDnsApiRecordsGetRequest) Execute() ([]Record, *_nethttp.Response, GenericOpenAPIError) {
	return r.ApiService.DnsApiRecordsGetExecute(r)
}

/*
 * DnsApiRecordsGet Retrieves the DNS zone's resource records
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiDnsApiRecordsGetRequest
 */
func (a *RecordsApiService) DnsApiRecordsGet(ctx _context.Context) ApiDnsApiRecordsGetRequest {
	return ApiDnsApiRecordsGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 * @return []Record
 */
func (a *RecordsApiService) DnsApiRecordsGetExecute(r ApiDnsApiRecordsGetRequest) ([]Record, *_nethttp.Response, GenericOpenAPIError) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		executionError       GenericOpenAPIError
		localVarReturnValue  []Record
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RecordsApiService.DnsApiRecordsGet")
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarPath := localBasePath + "/dns/api/Records"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.zone == nil {
		executionError.error = "zone is required and must be specified"
		return localVarReturnValue, nil, executionError
	}
	if r.xApiOptions == nil {
		executionError.error = "xApiOptions is required and must be specified"
		return localVarReturnValue, nil, executionError
	}

	localVarQueryParams.Add("Zone", parameterToString(*r.zone, ""))
	if r.recordType != nil {
		localVarQueryParams.Add("RecordType", parameterToString(*r.recordType, ""))
	}
	if r.name != nil {
		localVarQueryParams.Add("Name", parameterToString(*r.name, ""))
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["x-api-options"] = parameterToString(*r.xApiOptions, "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, executionError
}

type ApiDnsApiRecordsPostRequest struct {
	ctx                      _context.Context
	ApiService               RecordsApi
	xApiOptions              *string
	createRecordRequestModel *CreateRecordRequestModel
}

func (r ApiDnsApiRecordsPostRequest) XApiOptions(xApiOptions string) ApiDnsApiRecordsPostRequest {
	r.xApiOptions = &xApiOptions
	return r
}
func (r ApiDnsApiRecordsPostRequest) CreateRecordRequestModel(createRecordRequestModel CreateRecordRequestModel) ApiDnsApiRecordsPostRequest {
	r.createRecordRequestModel = &createRecordRequestModel
	return r
}

func (r ApiDnsApiRecordsPostRequest) Execute() (Record, *_nethttp.Response, GenericOpenAPIError) {
	return r.ApiService.DnsApiRecordsPostExecute(r)
}

/*
 * DnsApiRecordsPost Creates a new DNS resource record
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiDnsApiRecordsPostRequest
 */
func (a *RecordsApiService) DnsApiRecordsPost(ctx _context.Context) ApiDnsApiRecordsPostRequest {
	return ApiDnsApiRecordsPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 * @return Record
 */
func (a *RecordsApiService) DnsApiRecordsPostExecute(r ApiDnsApiRecordsPostRequest) (Record, *_nethttp.Response, GenericOpenAPIError) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		executionError       GenericOpenAPIError
		localVarReturnValue  Record
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "RecordsApiService.DnsApiRecordsPost")
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarPath := localBasePath + "/dns/api/Records"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xApiOptions == nil {
		executionError.error = "xApiOptions is required and must be specified"
		return localVarReturnValue, nil, executionError
	}
	if r.createRecordRequestModel == nil {
		executionError.error = "createRecordRequestModel is required and must be specified"
		return localVarReturnValue, nil, executionError
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/_*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["x-api-options"] = parameterToString(*r.xApiOptions, "")
	// body params
	localVarPostBody = r.createRecordRequestModel
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, nil, executionError
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		executionError.error = err.Error()
		return localVarReturnValue, localVarHTTPResponse, executionError
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, executionError
}
