openapi: 3.0.1
info:
  title: Fava - OpenApi Gateway - DNS
  version: v1
servers:
- url: /
security:
- oidc:
  - fava_business_api
  - fava_credentials_api
  - fava_openapi_gateway
  - pinto_citadel
  - pinto_nexus
paths:
  /dns/api/Records:
    delete:
      parameters:
      - description: Name of the DNS zone to delete a record of.
        explode: true
        in: query
        name: Zone
        required: true
        schema:
          type: string
        style: form
      - description: The record type of the record to delete.
        explode: true
        in: query
        name: RecordType
        required: true
        schema:
          $ref: '#/components/schemas/RecordType'
        style: form
      - description: The record name of the record to delete.
        explode: true
        in: query
        name: Name
        required: true
        schema:
          type: string
        style: form
      - description: "Data used to access the API <br /><br />\r\nSchema: <br />\r\
          \n{ <br />\r\n\"access_options\": { <br />\r\n\"provider\": \"provider\"\
          , <br />\r\n\"environment\": \"environment\", <br />\r\n\"credentials_id\"\
          : \"00000000-0000-0000-0000-000000000000\" <br />\r\n}, <br />\r\n\"meta\"\
          : { <br />\r\n\"additionalKey\": \"keyValue\" <br />\r\n} <br />\r\n}"
        explode: false
        in: header
        name: x-api-options
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "204":
          description: Successfully deleted
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Something went horribly wrong on the server side.
      summary: Deletes records which match the specified criterias
      tags:
      - Records
    get:
      parameters:
      - description: DNS zone to query.
        explode: true
        in: query
        name: Zone
        required: true
        schema:
          type: string
        style: form
      - description: Filter by the record type.
        explode: true
        in: query
        name: RecordType
        required: false
        schema:
          $ref: '#/components/schemas/RecordType'
        style: form
      - description: Filter by the record name.
        explode: true
        in: query
        name: Name
        required: false
        schema:
          type: string
        style: form
      - description: "Data used to access the API <br /><br />\r\nSchema: <br />\r\
          \n{ <br />\r\n\"access_options\": { <br />\r\n\"provider\": \"provider\"\
          , <br />\r\n\"environment\": \"environment\", <br />\r\n\"credentials_id\"\
          : \"00000000-0000-0000-0000-000000000000\" <br />\r\n}, <br />\r\n\"meta\"\
          : { <br />\r\n\"additionalKey\": \"keyValue\" <br />\r\n} <br />\r\n}"
        explode: false
        in: header
        name: x-api-options
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/Record'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Record'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/Record'
                type: array
          description: Returns the DNS records of the specified DNS zone
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "500":
          description: Something went horribly wrong on the server side.
      summary: Retrieves the DNS zone's resource records
      tags:
      - Records
    post:
      parameters:
      - description: "Data used to access the API <br /><br />\r\nSchema: <br />\r\
          \n{ <br />\r\n\"access_options\": { <br />\r\n\"provider\": \"provider\"\
          , <br />\r\n\"environment\": \"environment\", <br />\r\n\"credentials_id\"\
          : \"00000000-0000-0000-0000-000000000000\" <br />\r\n}, <br />\r\n\"meta\"\
          : { <br />\r\n\"additionalKey\": \"keyValue\" <br />\r\n} <br />\r\n}"
        explode: false
        in: header
        name: x-api-options
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRecordRequestModel'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateRecordRequestModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateRecordRequestModel'
        description: Data used to create a DNS resource record
        required: true
      responses:
        "201":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Record'
            application/json:
              schema:
                $ref: '#/components/schemas/Record'
            text/json:
              schema:
                $ref: '#/components/schemas/Record'
          description: Returns the newly created item
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "409":
          description: Conflict
        "500":
          description: Something went horribly wrong on the server side.
      summary: Creates a new DNS resource record
      tags:
      - Records
  /dns/api/Zones:
    delete:
      parameters:
      - description: Name of the DNS zone to delete.
        explode: true
        in: query
        name: Name
        required: true
        schema:
          type: string
        style: form
      - description: "Data used to access the API <br /><br />\r\nSchema: <br />\r\
          \n{ <br />\r\n\"access_options\": { <br />\r\n\"provider\": \"provider\"\
          , <br />\r\n\"environment\": \"environment\", <br />\r\n\"credentials_id\"\
          : \"00000000-0000-0000-0000-000000000000\" <br />\r\n}, <br />\r\n\"meta\"\
          : { <br />\r\n\"additionalKey\": \"keyValue\" <br />\r\n} <br />\r\n}"
        explode: false
        in: header
        name: x-api-options
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: Success
        "204":
          description: Zone was successfully deleted
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: DNS zone not found
        "500":
          description: Something went horribly wrong on the server side.
      summary: Deletes a DNS zone from the passed provider
      tags:
      - Zones
    get:
      parameters:
      - description: "Data used to access the API <br /><br />\r\nSchema: <br />\r\
          \n{ <br />\r\n\"access_options\": { <br />\r\n\"provider\": \"provider\"\
          , <br />\r\n\"environment\": \"environment\", <br />\r\n\"credentials_id\"\
          : \"00000000-0000-0000-0000-000000000000\" <br />\r\n}, <br />\r\n\"meta\"\
          : { <br />\r\n\"additionalKey\": \"keyValue\" <br />\r\n} <br />\r\n}"
        explode: false
        in: header
        name: x-api-options
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Zone'
                type: array
          description: List of DNS zones associated with the account
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: DNS zone not found
        "500":
          description: Something went horribly wrong on the server side.
      summary: Retrieves the DNS zones assigned to the account
      tags:
      - Zones
    post:
      parameters:
      - description: "Data used to access the API <br /><br />\r\nSchema: <br />\r\
          \n{ <br />\r\n\"access_options\": { <br />\r\n\"provider\": \"provider\"\
          , <br />\r\n\"environment\": \"environment\", <br />\r\n\"credentials_id\"\
          : \"00000000-0000-0000-0000-000000000000\" <br />\r\n}, <br />\r\n\"meta\"\
          : { <br />\r\n\"additionalKey\": \"keyValue\" <br />\r\n} <br />\r\n}"
        explode: false
        in: header
        name: x-api-options
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateZoneRequestModel'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateZoneRequestModel'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateZoneRequestModel'
        description: Data used to create a DNS zone
        required: true
      responses:
        "201":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Zone'
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
            text/json:
              schema:
                $ref: '#/components/schemas/Zone'
          description: Returns the newly created DNS zone
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "409":
          description: Conflict
        "500":
          description: Something went horribly wrong on the server side.
      summary: Creates a new DNS zone
      tags:
      - Zones
  /dns/api/Zones/{zone}:
    get:
      parameters:
      - description: The name of the zone to query.
        explode: false
        in: path
        name: zone
        required: true
        schema:
          type: string
        style: simple
      - description: "Data used to access the API <br /><br />\r\nSchema: <br />\r\
          \n{ <br />\r\n\"access_options\": { <br />\r\n\"provider\": \"provider\"\
          , <br />\r\n\"environment\": \"environment\", <br />\r\n\"credentials_id\"\
          : \"00000000-0000-0000-0000-000000000000\" <br />\r\n}, <br />\r\n\"meta\"\
          : { <br />\r\n\"additionalKey\": \"keyValue\" <br />\r\n} <br />\r\n}"
        explode: false
        in: header
        name: x-api-options
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Zone'
            application/json:
              schema:
                $ref: '#/components/schemas/Zone'
            text/json:
              schema:
                $ref: '#/components/schemas/Zone'
          description: Successfully loaded DNS zone
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "404":
          description: DNS zone not found
        "500":
          description: Something went horribly wrong on the server side.
      summary: Loads the specified DNS zone
      tags:
      - Zones
components:
  schemas:
    CreateRecordRequestModel:
      additionalProperties: false
      example:
        data: data
        zone: zone
        name: name
        ttl: 0
      properties:
        zone:
          description: Name of the DNS zone to create a record for.
          type: string
        name:
          description: Name of the DNS record to create.
          type: string
        class:
          $ref: '#/components/schemas/RecordClass'
        type:
          $ref: '#/components/schemas/RecordType'
        data:
          description: The data of the record to create,
          type: string
        ttl:
          description: The time to live of the record to create.
          format: int32
          type: integer
      required:
      - data
      - name
      - type
      - zone
      type: object
    CreateZoneRequestModel:
      additionalProperties: false
      example:
        name: name
      properties:
        name:
          description: Name of the DNS zone to create.
          type: string
      required:
      - name
      type: object
    Record:
      additionalProperties: false
      example:
        data: data
        name: name
        ttl: 0
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/RecordType'
        class:
          $ref: '#/components/schemas/RecordClass'
        ttl:
          format: int32
          type: integer
        data:
          type: string
      required:
      - class
      - data
      - name
      - type
      type: object
    RecordClass:
      description: "Resource record classes\r\nas defined in\r\n<see href=\"https://tools.ietf.org/html/rfc1035#section-3.2.4\"\
        >rfc1035</see>"
      enum:
      - IN
      - CS
      - CH
      - HS
      type: string
    RecordType:
      description: "Resource record types\r\nas defined in\r\n<see href=\"https://tools.ietf.org/html/rfc1035#section-3.2.2\"\
        >rfc1035</see>"
      enum:
      - A
      - NS
      - CNAME
      - SOA
      - PTR
      - MX
      - TXT
      - SRV
      - AAAA
      - SPF
      type: string
    Zone:
      additionalProperties: false
      example:
        name: name
      properties:
        name:
          type: string
      required:
      - name
      type: object
  securitySchemes:
    oidc:
      flows:
        authorizationCode:
          authorizationUrl: https://auth.test.camao.domains.fascicularis.de/connect/authorize
          scopes:
            fava_business_api: Fava - Business - API
            fava_credentials_api: Fava - Credentials - API
            fava_openapi_gateway: Fava - OpenApiGateway - API
            pinto_citadel: Pinto - Citadel - Certificates - API
            pinto_nexus: Pinto - Nexus - DNS - API
          tokenUrl: https://auth.test.camao.domains.fascicularis.de/connect/token
      type: oauth2
